### PR TITLE
Updated the icon for the 30th season

### PR DESCRIPTION
**Pull request by hackthis02**

### CODE REVIEW

**Comment by eracknaphobia** [comment]
Although I would like to improve the icon image not sure this is the one. Quality is a bit low and it'd need changed once season 31 starts.

**Comment by hackthis02** [comment]
I don't think they do a new logo for each season. but 30 was a big deal.

**Comment by eracknaphobia** [comment]
That's true, Do you have a better quality version of this image? Preferably 512x512.

**Comment by hackthis02** [comment]
Yeah I looks around and this was the best quality I could find.

**Pull request closed without merging**
