### PR TITLE
Added a random episode button

### PR DESCRIPTION
**Pull request by hackthis02**
Added a random episode button to mimic the functionality find on the site/app

### CODE REVIEW

**Comment by hackthis02** [comment]
I'm not sure why, but on my PC the listSeason() call in getStream(url) fires successfully, but it doesn't seem to work on my Pi3B. If you have any thoughts or ideas, I'm all ears.

**Comment by eracknaphobia** [comment]
> Added a random episode button to mimic the functionality find on the site/app

Why not use this to get a random episode: http://www.simpsonsworld.com/random/episode



> I'm not sure why, but on my PC the listSeason() call in getStream(url) fires successfully, but it doesn't seem to work on my Pi3B. If you have any thoughts or ideas, I'm all ears.

Have you tried enabling debug mode and checking what the logs say?

**Comment by hackthis02** [comment]
> Why not use this to get a random episode: http://www.simpsonsworld.com/random/episode

I'm going to be honest. I'm more of a C variance programmer. I have a rudimentary knowledge of rest APIs and am working on these projects as a way to learn more about python. So I'm unaware of all the endpoint for the FX site. When I put 'http://www.simpsonsworld.com/random/episode' into postman I'm unable to extract a video_url for an episode. Which is why I did it the way I did. If you have the endpoint for random episodes I'll gladly change my logic.

>Have you tried enabling debug mode and checking what the logs say?

I did. I didn't see anything right away. I'm still looking tho.

**Comment by eracknaphobia** [comment]
I'll take  a look tonight and see what call my android tv makes for random episode and let you know what I find. I'm not trying to be critical, what you have would work, but if we can have their servers do that for us then that's less code that we have to maintain.

**Comment by hackthis02** [comment]
No that makes total sense and you're actually one of the least critical devs I've worked with for Kodi. It's refreshing.

**Comment by hackthis02** [comment]
I'm guessing your Android TV doesn't make a unique random episode call?

**Comment by eracknaphobia** [comment]
No luck finding a good random episode endpoint. It would have been just as much code, if not more.

**Pull request merged**
